name: ossf-scorecard
on: workflow_call

jobs:
  ossf-scorecard:
    name: ossf-scorecard
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ github.token }}
          publish_results: true
