# Required Permissions:
#   security-events: write
#   id-token: write

name: ossf-scorecard
on: workflow_call

jobs:
  ossf-scorecard:
    name: ossf-scorecard
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@v2.4.2
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.OSSF_SCORECARD_TOKEN }}
          publish_results: true
