name: reactions-based-pr-label
on: 
  workflow_call:
    inputs:
      reaction:
        description: "The reaction type to check for"
        required: true
        type: string

      reaction-count:
        description: "The minimum number of reactions required to add the label"
        required: true
        type: number

      label:
        description: "The label to add / remove based on the reaction count"
        required: true
        type: string

jobs:
  reactions-based-pr-label:
    name: reactions-based-pr-label
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.LABEL_PRS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get Open PR numbers
        id: get-open-prs
        run: |
          OPEN_PR_NUMS=$(gh api "/repos/${GITHUB_REPOSITORY}/pulls?state=open" -q '.[].number' | tr '\n' ' ' | sed 's/[[:space:]]*$//')

          if [ -z "$OPEN_PR_NUMS" ]; then
            echo "No open PRs found."
            exit 0
          fi

          echo "The following PR numbers are open: $OPEN_PR_NUMS"
          echo "OPEN_PR_NUMS=$OPEN_PR_NUMS" >> $GITHUB_ENV
          echo "open_prs=true" >> $GITHUB_OUTPUT

      - name: Get PR Reaction Counts and Manage Labels
        if: steps.get-open-prs.outputs.open_prs == 'true'
        run: |
          OPEN_PR_NUMS="${{ env.OPEN_PR_NUMS }}"
          eval "set -- $OPEN_PR_NUMS"

          for PR_NUMBER in "$@"; do

            PR_AUTHOR=$(gh api repos/${GITHUB_REPOSITORY}/pulls/$PR_NUMBER --jq '.user.login')
            
            REACTION_COUNT_EXCLUDING_AUTHOR=$(gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "/repos/${GITHUB_REPOSITORY}/issues/$PR_NUMBER/reactions" \
              -q "[.[] | select(.content == \${{ inputs.reaction }}\" and .user.login != \"$PR_AUTHOR\")] | length")   
            echo "PR #$PR_NUMBER has $REACTION_COUNT_EXCLUDING_AUTHOR ${{ inputs.reaction }} reactions, excluding from the author."

            if [ "$REACTION_COUNT_EXCLUDING_AUTHOR" -ge ${{ inputs.reaction-count }} ]; then
              echo "Adding ${{ inputs.label }} label to PR #$PR_NUMBER."
              gh api -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "/repos/${GITHUB_REPOSITORY}/issues/$PR_NUMBER/labels" \
                -f "labels[]=${{ inputs.label }}" > /dev/null
            
            else
              echo "PR #$PR_NUMBER does not have enough ${{ inputs.reaction }} reactions."

              HAS_LABEL=$(gh api \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "/repos/${GITHUB_REPOSITORY}/issues/$PR_NUMBER/labels" \
                -q '[.[] | select(.name == ${{ inputs.label }})] | length')
              
              if [ "$HAS_LABEL" -gt 0 ]; then
                echo "PR #$PR_NUMBER has the ${{ inputs.label }} label."
                echo "Removing ${{ inputs.label }} label from PR #$PR_NUMBER."
                gh api -X DELETE \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  "/repos/${GITHUB_REPOSITORY}/issues/$PR_NUMBER/labels/${{ inputs.label }}" > /dev/null
              fi
            fi
          done
