# Required Permissions:
#   pull-requests: read

name: validate-pr-title
on: workflow_call
permissions:
  contents: read
  pull-requests: read

jobs:
  validate-pr-title:
    name: validate-pr-title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
