name: validate-pr-title
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened

jobs:
  validate-pr-title:
    name: validate-pr-title
    permissions:
      contents: read
      pull-requests: read
    uses: mindbuttergold/github-actions-reusable-workflows/.github/workflows/validate-pr-title.yaml@v1.0.0
    secrets: inherit
