name: check-community-approval
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
permissions:
  contents: read

jobs:
  check-community-approval:
    name: check-community-approval
    uses: ./.github/workflows/check-community-approval.yaml
    secrets: inherit
