name: Semver Release
on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/semver-release.yaml
    secrets: inherit
