name: validate-pr-title
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-pr-title:
    name: validate-pr-title
    uses: ./.github/workflows/validate-pr-title.yaml
    secrets: inherit
